version: 0.2
phases:
  install:
    commands:
      - pip install yq
      - pip install boto3
  pre_build:
    commands:
      - echo "Starting CliXX deployment"
      - echo "more commands"
  build:
    on-failure: ABORT
    commands:
      - echo starting build on `date`
      - echo "Creating CliXX Security Group for apps and database"
      - |
          flag='delete'
          if [[ $flag == 'restore' ]]
          then
              python restore_db_instance_from_db_snapshot.py
          elif [[ $flag == 'deploy' ]]
          then
              python deploy_clixx.py
          elif [[ $flag == 'delete' ]]
          then
              python delete_db_instance.py
          elif [[ $flag == 'assume' ]]
          then
              python assume_role.py
          fi
  post_build:
    commands:
      - echo Build completed on `date`