version: 0.2
phases:
  install:
    commands:
      - pip install yq
      - pip install boto3
  pre_build:
    commands:
      - echo "Starting CliXX deployment"
      - echo "more commands"
  build:
    on-failure: ABORT
    commands:
      - echo starting build on `date`
      - echo "Creating CliXX Security Group for apps and database"
      - |
          flag='deploy_efs'  # Set flag value; make sure this is dynamically set as needed

          if [[ $flag == 'restore' ]]; then
            echo "Restoring DB instance from snapshot..."
            python restore_db_instance_from_db_snapshot.py
          elif [[ $flag == 'deploy' ]]; then
            echo "Deploying CLiXX..."
            python deploy_clixx.py
          elif [[ $flag == 'deploy_efs' ]]; then
            echo "Deploying CLiXX mounted on EFS..."
            python deploy_clixx_EFS.py
          elif [[ $flag == 'delete' ]]; then
            echo "Deleting DB instance..."
            python delete_db_instance.py
          elif [[ $flag == 'assume' ]]; then
            echo "Assuming role..."
            python assume_role.py
          else
            echo "Invalid option. Please set the flag correctly."
          fi

  post_build:
    commands:
      - echo Build completed on `date`

